[package]
name = "zero2prod" # name of lib
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
path = "src/lib.rs"

[[bin]]
path = "src/main.rs"
name = "zero2prod" # this is the file name of the binary


[dependencies]
actix-web = "4.0.0-beta.16"
tokio = { version = "1.15.0",features = ["macros", "rt-multi-thread"]}
serde = { version = "1.0.133", features = ["derive"] }
reqwest = "0.11.7"
config = "0.11.0"

[dependencies.sqlx]
version = "0.5.10"
features = [
    "runtime-actix-rustls",
    "macros",
    "postgres",
    "uuid", 
    "chrono",
    "migrate"
]

