#! configuration/base.yaml

# 6379 is Redis' default port
redis_uri: "redis://127.0.0.1:6379"
application:
  port: 8000
  hmac_secret: "super-long-and-secret-key-needed-to-verify-message-integrity-more-than-64"
database:
  host: "localhost"
  port: 5432
  username: "postgres"
  password: "password"
  database_name: "newslettery"
  migrate: false

email_client:
  base_url: "localhost"
  sender_email: "test@gmail.com"
  authorization_token: "my-secret-token"
  timeout_milliseconds: 10000