#! configuration/production.yaml
application:
  host: 0.0.0.0
database:
  require_ssl: true

email_client:
  base_url: "https://api.postmarkapp.com/email"
  sender_email: "yudhya.wicaksono@delameta.com"